language: python
python: 3.7.2
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U black
install:
  - pip install -r requirements.txt
script:
  - black --check .
  - python -m pytest --cov=src --cov-fail-under=80 tests/*