name: default

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check formatting with Black
      run: |
        black --check .
    - name: Test with pytest and check coverage
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=src --cov-fail-under=75 --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html tests/*